# Dockerfile.cron
FROM debian:latest

RUN apt-get update && apt-get install -y cron rsync

COPY cron.sh /root/cron.sh
COPY backup_script.sh /root/backup_script.sh

RUN chmod +x /root/cron.sh /root/backup_script.sh

CMD ["bash", "/root/cron.sh"]

