version: "3"

services:
  nextcloud:
    image: nextcloud
    restart: always
    env_file:
      - ./nextcloud.env
    volumes:
      - /root/docker_compose/nextcloud:/var/www/html
    depends_on:
      - mariadb
    networks:
      - nextcloud_network

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - ./db.env
    volumes:
      - /root/docker_compose/mariadb:/var/lib/mysql
    networks:
      - nextcloud_network

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/docker_compose/nginx.conf:/etc/nginx/nginx.conf
      - /root/docker_compose/ssl:/etc/nginx/ssl
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

networks:
  nextcloud_network:

