FROM ubuntu:latest

RUN apt-get update && apt-get install -y rsync ssh

COPY backup_syncro.sh /backup_syncro.sh

COPY id_ed25519 /root/.ssh/id_ed25519
COPY known_hosts /root/.ssh/known_hosts

RUN chmod +x /backup_syncro.sh

CMD ["/bin/bash", "-c", "/backup_syncro.sh"]

