version: "3"

services:
  nextcloud:
    image: nextcloud
    restart: always
    env_file:
      - ./nextcloud.env
    volumes:
      - ./nextcloud:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - ./db.env
    volumes:
      - ./mariadb:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - nextcloud

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  nextcloud-exporter:
    image: xperimental/nextcloud-exporter:latest
    environment:
      - NEXTCLOUD_SERVER=https://nextcloudflow.local # Remplacez par l'URL ou l'adresse IP de votre serveur Nextcloud.
      - NEXTCLOUD_USERNAME=retr0
      - NEXTCLOUD_PASSWORD=t271SF121@N # Remplacez par le mot de passe réel.
      - NEXTCLOUD_TLS_SKIP_VERIFY=true
    ports:
      - 9205:9205
    depends_on:
      - nextcloud

volumes:
  grafana_data:

