FROM ubuntu:latest

# Installation de Docker
RUN apt-get update && apt-get install -y rsync ssh docker.io docker docker-compose

# Copie du script de sauvegarde
COPY restauration.sh /restauration.sh

# Copie des chemins vers les clés ssh
COPY id_ed25519 /root/.ssh/id_ed25519
COPY known_hosts /root/.ssh/known_hosts


# Définition de l'exécution du script au démarrage du conteneur
CMD ["/restauration.sh"]
