global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'nextcloud'
    static_configs:
      - targets: ['nextcloud-exporter:9205'] # Ici, utilisez le nom de service de votre exporter dans le fichier docker-compose, qui est 'nextcloud-exporter'

