{
 "title": "Nextcloud",
 "description": "Export Nextcloud metrics",
 "tags": [
  "cloud",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Free Space Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes", "legendFormat": "Free Space (GB)" }
   ]
  },
  {
   "title": "Nextcloud Up ?",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(nextcloud_up)" }
   ]
  },
  {
   "title": "Files Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_files_total", "legendFormat": "Files Total" }
   ]
  },
  {
   "title": "Shares",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nextcloud_shares_federated_total)",
     "legendFormat": "Federated Total"
    },
    { "expr": "sum(nextcloud_shares_total)", "legendFormat": "Total Shares" }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_scrape_errors_total", "legendFormat": "Scrape Errors Total" }
   ]
  },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_users_total", "legendFormat": "Users Total" },
    { "expr": "nextcloud_active_users_total", "legendFormat": "Users Active" }
   ]
  }
 ]
}